FROM  node:16-alpine

WORKDIR /myapp
RUN apk apk update && apk upgrade && apk update
COPY package.json ./
RUN npm install && npm cache clean --force

COPY  ./src ./src
EXPOSE 3000

CMD [ "node", "src/app.js" ]